### ISSUE TITLE
train مدل XTTS

### ISSUE THREAD

**Issue by kontorol** [karim23657/Persian-tts-coqui#15]
برای train کردن مدل xtts کدوم Dataset رو پیشنهاد می کنید ؟

**Comment by karim23657** [comment]
سلام @kontorol 
1. https://www.kaggle.com/datasets/magnoliasis/persian-tts-dataset-famale
2. https://www.kaggle.com/datasets/magnoliasis/persian-tts-dataset-male

خوشحال میشم کدها و مدل های ترین شدتون رو با ما به اشتراک بزارید
