### ISSUE TITLE
مشکل در نصب tts توی کولب

### ISSUE THREAD

**Issue by alighafoori** [karim23657/Persian-tts-coqui#8]
من توی نصب tts توی کولب این خطا میگیرم چیکار باید بکنم
![image](https://github.com/karim23657/Persian-tts-coqui/assets/10322259/0f8c48fe-e3ac-4d0e-b209-d9181bf50f39)

**Comment by kfatehi** [comment]
something else on your machine has installed an incompatible version of protobufs.

سعی کنید از یک وضعیت تازه نصب کنید، یا ابتدا آن وابستگی را حذف کنید.

I exercised the first option by using [docker](https://github.com/kfatehi/persian-tts-server/blob/master/Dockerfile) but I don't know how easy that is for you to do within the notebook environment.

**Comment by alighafoori** [comment]
I solved issue with virtualenv thanks
![image](https://github.com/karim23657/Persian-tts-coqui/assets/10322259/36ae8939-337d-4226-a192-2be926af1dc4)
